FROM golang:1.25-alpine AS builder

WORKDIR /app

RUN apk add --no-cache git

COPY go.mod go.sum ./
RUN go mod download

COPY . .
RUN go mod tidy
RUN go build -buildvcs=false -ldflags="-w -s" -o /main .

FROM alpine:3.19

RUN apk add --no-cache ca-certificates curl postgresql-client

WORKDIR /app

COPY --from=builder /main .
COPY --from=builder /app/internal/config ./internal/config

EXPOSE 8080

CMD ["/app/main"]
